name: "Minio Action"

description: "Manipulate S3 objects on Min.IO storage"

inputs:
  minio_url:
    required: true
    description: "The minio storage URL"
  minio_bucket:
    required: true
    description: "The minio bucket to operate on"
  minio_access_key:
    required: true
    description: "The minio access key ID"
  minio_secret_key:
    required: true
    description: "The minio secret key ID"
  generate_share_url:
    required: false
    description: "Generate 7-days public URL for a minio object"
    default: false
  upload_file:
    required: false
    description: "Enable action to upload a file to minio storage"
    default: false
  upload_file_path:
    required: false
    description: "The source path for the file to be uploaded"
  upload_file_s3_path:
    required: false
    description: "The target path on minio storage for the file to be uploaded"
  download_file:
    required: false
    description: "Enable action to download a file from minio storage"
    default: false
  download_file_path:
    required: false
    description: "The target path for the file to be downloaded to"
  download_file_s3_path:
    required: false
    description: "The source path on minio storage for the file to be downloaded"

runs:
  using: "composite"
  steps:
    - name: Set up minio configuration
      uses: docker://minio/mc
      with:
        args: 