name: "Send Slack notification from Github"

description: "Send Slack notification from Github"

inputs:
  slack_webhook_url:
    required: true
    description: "Slack webhook URL"

runs:
  using: "composite"
  steps:
    - name: Send build failure alert to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Build for *${{ github.event.repository.name }}* result: *${{ job.status }}*\n\n*<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}|Github Action Log>*\n\nCommit <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|*${{ github.event.head_commit.id }}*>\n\nCommit author: *${{ github.event.head_commit.author.email }}*"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK