# This workflow will run maven checks, to be used with PRs

name: Run Jave code scans and code style checks

on:
  workflow_call:
    inputs:
      repo:
        description: 'Repo to checkout'
        type: string
        required: true
    secrets:
      slack_webhook_url:
        description: 'Slack webhook URL for notifications'
        required: false
      TOKEN_RW:
        description: 'Github token'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    permissions:
      contents: read
      packages: write

    steps:
      
    - name: Check slack secrets
      run: |
        echo "URL from ORG secrets: ${SLACK_URL}"
        echo "URL from input secrets: ${SLACK_INPUT_URL}"
      env:
        SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_INPUT_URL: ${{ secrets.slack_webhook_url }}

    - name: Check deployment status in Kubernetes
      run: |
        echo ${B64_KUBECONFIG} | base64 -d > ${KUBECONFIG}
        kubectl config view
        kubectl get pods
      env:
        B64_KUBECONFIG: ${{ secrets.K8S_DEV_KUBECONFIG_B64 }}
        KUBECONFIG: /tmp/kubeconfig

    - name: Checkout Flux repo
      uses: actions/checkout@master
      with:
        ref: main
        repository: ${{ github.repository_owner }}/${{ inputs.repo }}
        token: ${{ secrets.TOKEN_RW }}