# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build package with Maven and publish as container image to GitHub Packages

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Version of JDK to run builds on'
        type: string
        required: false
        default: '11'
      gitversion_image_version:
        description: 'Version of GitVersion docker image to use'
        type: string
        required: false
        default: '5.10.1-alpine.3.14-6.0'
      project_subdirectory:
        description: 'The subdirectory relative to repository root where project is located'
        type: string
        required: false
      tomcat_root_context:
        description: 'Whether to use root context in Tomcat docker image'
        type: boolean
        required: false
        default: false
    outputs:
      app_version:
        description: "The generated version from the build"
        value: ${{ jobs.build.outputs.app_version }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    outputs:
      app_version: ${{ steps.version.outputs.image_tag }}

    # Set working directory for all steps at once
    defaults:
      run:
        working-directory: ${{ inputs.project_subdirectory || '.' }} 

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # requirement of GitVersion
        fetch-depth: 0   # requirement of GitVersion

    ### Versioning

    - name: Generate version
      id: version
      working-directory: '.'
      run: |
        set -euo pipefail

        echo "Branch is ${GITHUB_REF_NAME}"

        ### This is specific to using GitVersion with GitHub 
        ### 'develop' and 'main' branches if they exist need to be checked out explicitly prior to GitVersion run
        git checkout develop || true
        git checkout main || true
        git checkout ${GITHUB_REF_NAME}

        docker run --rm -v "$(pwd):/repo" gittools/gitversion:${GITVERSION_IMAGE_VERSION} \
          /nocache \
          /nonormalize \
          /verbosity Verbose \
          /overrideconfig assembly-versioning-format='{Major}.{Minor}.{Patch}-{PreReleaseLabel}${ShortSha}' \
          /targetpath /repo | tee /tmp/version 

        VERSION_LONG=$(jq -r '.AssemblySemVer' /tmp/version)
        VERSION_SHORT=$(jq -r '.MajorMinorPatch' /tmp/version)
        echo "Long Version is ${VERSION_LONG}"
        echo "Short Version is ${VERSION_SHORT}"
        
        if [ "${GITHUB_REF}" = 'refs/heads/main' ]
        then
          echo ::set-output name=image_tag::${VERSION_SHORT}
        else
          echo ::set-output name=image_tag::${VERSION_LONG}
        fi
      env:
        GITVERSION_IMAGE_VERSION: ${{ inputs.gitversion_image_version }}
        
    - name: Add tag to repository
      if: contains('refs/heads/main', github.ref)
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        custom_tag: ${{ steps.version.outputs.image_tag }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    ### Pre-build actions

    # Use generic Dockerfile for all builds
    - name: Create Dockerfile
      if: github.event_name != 'pull_request'
      run: |
        cat > Dockerfile <<'EOF'
        FROM tomcat:9.0-jre11-openjdk-slim-bullseye

        ARG WAIT_TIMEOUT
        ARG PORT

        ENV WAIT_TIMEOUT ${WAIT_TIMEOUT:-'60s'}
        ENV PORT ${PORT:-8080}

        RUN addgroup --gid 1000 www-group && adduser --system --disabled-password --gecos "" --gid 1000 --uid 1000 www-user
        RUN chown -hR 1000:1000 ${CATALINA_HOME}

        EXPOSE ${PORT}
        EOF

        if [ "${TOMCAT_ROOT_CTX}" = true ]; then
        cat >> Dockerfile <<'EOF'

        COPY --chown=1000:root target/*.war ${CATALINA_HOME}/webapps/ROOT.war

        EOF
        else
        cat >> Dockerfile <<'EOF'

        COPY --chown=1000:root target/*.war ${CATALINA_HOME}/webapps/

        EOF
        fi

        cat >> Dockerfile <<'EOF'
        USER 1000

        CMD ["catalina.sh", "run"]
        EOF
      env:
        TOMCAT_ROOT_CTX: ${{ inputs.tomcat_root_context }}

    ### Build actions

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
        cache: maven

    - name: Package with Maven
      run: mvn -B clean package

    - name: Check the built files
      run: |
        ls -la 
        ls -la target/
        find . -type f -name *war*

    ### Publish actions

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      if: github.event_name != 'pull_request'
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          ${{ steps.version.outputs.image_tag }}
          type=ref,event=branch
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      id: build-and-push
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ${{ inputs.project_subdirectory || '.' }} 
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
