# This workflow will run maven checks, to be used with PRs

name: Run integration tests

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Version of JDK to run builds on'
        type: string
        required: false
        default: '11'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: pm-user
          MONGO_INITDB_ROOT_PASSWORD: pulsemusic
          MONGO_INITDB_DATABASE: pulsemusic-test
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
        cache: maven
      
    - name: Run code style check with Maven
      run: mvn -B clean install -Pintegration
